---
all:
  hosts:
    riak01:
      ansible_host: 192.168.33.11
      ansible_ssh_private_key_file: .vagrant/machines/riak01/virtualbox/private_key
    riak02:
      ansible_host: 192.168.33.12
      ansible_ssh_private_key_file: .vagrant/machines/riak02/virtualbox/private_key
    riak03:
      ansible_host: 192.168.33.13
      ansible_ssh_private_key_file: .vagrant/machines/riak03/virtualbox/private_key
    riak04:
      ansible_host: 192.168.33.14
      ansible_ssh_private_key_file: .vagrant/machines/riak04/virtualbox/private_key
    riak05:
      ansible_host: 192.168.33.15
      ansible_ssh_private_key_file: .vagrant/machines/riak05/virtualbox/private_key
  children:
    riak_nodes:
      hosts:
        riak0[1:5]: